### ISSUE TITLE
Adding scheduler for rotaion members

### ISSUE THREAD

**Issue by karoziya** [karoziya/TeamRotationActivity#1]
Проверка раз в день\час и т.п. что пора менять людей.
Try cron calculation period.
https://www.nuget.org/packages?q=cron
https://github.com/kevincolyar/CronNET?ysclid=lp27ftgkxx828591843

**Comment by Jenausmax** [comment]
Предлагаю использовать https://www.hangfire.io/
Отличная и простая вещь!

**Comment by karoziya** [comment]
Митинг каждую субботу 9:00,  меняй.
Каждый день в 9:20, каждую второую неделю в 10:15

Джобы - для ротаци
Нужен джоб которые висит и чекает постоянно надо ли запланировать ротацию.
Вычисляем дату след ротаци и запускаем scheduler джоб.
```
var jobId = BackgroundJob.Schedule(
    () => Console.WriteLine("Delayed!"),
    TimeSpan.FromDays(7));
```
